name: emoji
description: Emojis for Flutter, this package supports svg and png 72x72 emojis

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  characters: ^1.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  io: ^1.0.3

  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  dart_code_metrics: ^4.17.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/webp/
    # - assets/svg/