# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
enable-beta-ecosystems: true
updates:

  - package-ecosystem: "pub" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/package/component"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/package/core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/package/element"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/package/matter"
    schedule:
      interval: "weekly"