name: method_style_widgetbook
description: A Widgetbook for the method_style package.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^2.4.1
  widgetbook_annotation: ^2.1.0
  method_style:
  method_preview:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  widgetbook_generator: ^2.4.1
  device_frame: ^1.1.0

flutter:
  uses-material-design: true