name: method
description: Experiment with your thought.

version: 1.0.0+22081164
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  firebase_core: ^1.20.1
  firebase_crashlytics: ^2.8.7
  firebase_performance: ^0.8.2+2
  firebase_analytics: ^9.3.1
  firebase_remote_config: ^2.0.14
  firebase_app_installations: ^0.1.1+4
  firebase_app_check: ^0.0.6+19
  firebase_in_app_messaging: ^0.6.0+21

  core:
  matter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  melos: ^2.6.0
  dart_code_metrics: ^4.17.0

flutter:
