name: method_data
description: Repository for method.

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # RudderStack x Firebase SDK version podfile override
  # https://firebase.flutter.dev/docs/manual-installation#overriding-firebase-sdk-versions
  # $FirebaseSDKVersion = '8.15.0'

  firebase_core: ^2.4.0
  firebase_analytics: ^10.0.7
  firebase_crashlytics: ^3.0.7
  firebase_dynamic_links: ^5.0.10
  firebase_performance: ^0.9.0+7
  firebase_remote_config: ^3.0.7
  # firebase_app_installations: 0.1.0+11
  firebase_app_installations: ^0.2.1+6
  firebase_app_check: ^0.1.1+6
  firebase_in_app_messaging: ^0.7.0+8
  firebase_messaging: ^14.2.0

  rudder_sdk_flutter: ^2.2.0
  rudder_integration_firebase_flutter: ^1.0.1
  
  # flutter_segment: ^3.12.1

  # method_core:

dev_dependencies:
  dart_code_metrics: ^5.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
