name: method_settings_appearance
# description: 
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0

  go_router:

  method_style:
  method_monitoring_service:
  method_user_repository:

dev_dependencies:

  # Code Analysis

  method_analysis: 

  # Code Generation

  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.4 

  # Testing

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.0 
  mocktail: ^0.3.0 