name: method_core
description: method_core for method.

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

flutter:
  assets:
    - assets/

dependencies:
  built_collection: ^5.1.1
  collection: any
  # flutter:
  #   sdk: flutter
  # flutter_bloc: ^8.1.1
  # flutter_platform_widgets: ^2.0.0
  freezed_annotation: ^2.1.0
  # go_router: ^5.2.4
  # image_picker: ^0.8.5+3
  # intl: ^0.17.0
  json_annotation: ^4.6.0
  # lottie: ^2.0.0
  # provider: any
  quiver: ^3.1.0
  slugify: ^2.0.0
  uuid: ^3.0.6
  bloc: ^8.0.0
  
  # flutter_segment: ^3.12.1
  rudder_sdk_flutter: ^2.2.0
  
dev_dependencies:
  build_runner: ^2.2.0
  dart_code_metrics: ^5.2.1
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

  bloc_test: ^9.1.0
  mocktail: ^0.3.0
