// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA68nb1LK16_S094RFZ-cP-cULhy3kV6EU',
    appId: '1:74362590978:web:8f963787f6cebfa3f9141b',
    messagingSenderId: '74362590978',
    projectId: 'method-gcp-stg',
    authDomain: 'method-gcp-stg.firebaseapp.com',
    storageBucket: 'method-gcp-stg.appspot.com',
    measurementId: 'G-PJF16GQ3PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNUJ2gFP6YERkMbuHvxBkws19GKqqwBos',
    appId: '1:74362590978:android:9e377c740fe03787f9141b',
    messagingSenderId: '74362590978',
    projectId: 'method-gcp-stg',
    storageBucket: 'method-gcp-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjPj31xMj2VujHPfxrMp9dFXZJqJ8of60',
    appId: '1:74362590978:ios:5a44896fa394f718f9141b',
    messagingSenderId: '74362590978',
    projectId: 'method-gcp-stg',
    storageBucket: 'method-gcp-stg.appspot.com',
    iosClientId:
        '74362590978-83nqvubiotn7hr9i3j43qrrqor3h0954.apps.googleusercontent.com',
    iosBundleId: 'ch.thipok.method.stg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjPj31xMj2VujHPfxrMp9dFXZJqJ8of60',
    appId: '1:74362590978:ios:5a44896fa394f718f9141b',
    messagingSenderId: '74362590978',
    projectId: 'method-gcp-stg',
    storageBucket: 'method-gcp-stg.appspot.com',
    iosClientId:
        '74362590978-83nqvubiotn7hr9i3j43qrrqor3h0954.apps.googleusercontent.com',
    iosBundleId: 'ch.thipok.method.stg',
  );
}
