// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEkAhKEnt9KmxwdRmzGXxI9EDxd86fePQ',
    appId: '1:861458672220:web:98aeefffa52877df29d499',
    messagingSenderId: '861458672220',
    projectId: 'method-gcp-dev',
    authDomain: 'method-gcp-dev.firebaseapp.com',
    storageBucket: 'method-gcp-dev.appspot.com',
    measurementId: 'G-F45WQVLJDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBym0ETptdkm9BG7eKsiJxjTwh7vneCmK0',
    appId: '1:861458672220:android:155c1e9ba07510ac29d499',
    messagingSenderId: '861458672220',
    projectId: 'method-gcp-dev',
    storageBucket: 'method-gcp-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlOs9IhOANyHEb0PldfII4k30s822oWBM',
    appId: '1:861458672220:ios:b7fa81870a8cfe3029d499',
    messagingSenderId: '861458672220',
    projectId: 'method-gcp-dev',
    storageBucket: 'method-gcp-dev.appspot.com',
    iosClientId:
        '861458672220-mprfgep7mpt5dbgboi5mq2karur61r4r.apps.googleusercontent.com',
    iosBundleId: 'ch.thipok.method.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlOs9IhOANyHEb0PldfII4k30s822oWBM',
    appId: '1:861458672220:ios:b7fa81870a8cfe3029d499',
    messagingSenderId: '861458672220',
    projectId: 'method-gcp-dev',
    storageBucket: 'method-gcp-dev.appspot.com',
    iosClientId:
        '861458672220-mprfgep7mpt5dbgboi5mq2karur61r4r.apps.googleusercontent.com',
    iosBundleId: 'ch.thipok.method.dev',
  );
}
