// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPhlR_dnLpYEPwoLPp1FevznVld9C4T9I',
    appId: '1:233112850984:web:595a79be16cbbb250a9b1d',
    messagingSenderId: '233112850984',
    projectId: 'method-gcp-prd',
    authDomain: 'method-gcp-prd.firebaseapp.com',
    storageBucket: 'method-gcp-prd.appspot.com',
    measurementId: 'G-XXCN3KVGGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvoXp4_TL67ApxgExMtAok5CUtDlqlNVs',
    appId: '1:233112850984:android:b02dcbfa6efa02e50a9b1d',
    messagingSenderId: '233112850984',
    projectId: 'method-gcp-prd',
    storageBucket: 'method-gcp-prd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQc7hUq7xjsDJNwU2AT1lFaRqo21ixVzo',
    appId: '1:233112850984:ios:115c5098757cb5a90a9b1d',
    messagingSenderId: '233112850984',
    projectId: 'method-gcp-prd',
    storageBucket: 'method-gcp-prd.appspot.com',
    iosClientId:
        '233112850984-4g9j7a53rmjt35aiv89f5ohgq85nfgjq.apps.googleusercontent.com',
    iosBundleId: 'ch.thipok.method.prd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQc7hUq7xjsDJNwU2AT1lFaRqo21ixVzo',
    appId: '1:233112850984:ios:115c5098757cb5a90a9b1d',
    messagingSenderId: '233112850984',
    projectId: 'method-gcp-prd',
    storageBucket: 'method-gcp-prd.appspot.com',
    iosClientId:
        '233112850984-4g9j7a53rmjt35aiv89f5ohgq85nfgjq.apps.googleusercontent.com',
    iosBundleId: 'ch.thipok.method.prd',
  );
}
