name: method_style
description: Styles and UI Toolkit for the method.
# version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # modal_bottom_sheet: ^2.1.0
  linked_scroll_controller: ^0.2.0
  figma_squircle: ^0.5.3

  characters: ^1.1.0
  flutter_svg: ^1.0.0
  io: ^1.0.3

  path: ^1.8.0
  yaml: ^3.1.0
  image: ^3.2.2

  fluentui_system_icons: ^1.1.178
  gaimon: ^1.0.1
  dynamic_color: ^1.5.4


dev_dependencies:

  # Code Analysis

  method_analysis: 

  # Code Generation

  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.4 
  flutter_gen_runner: ^5.1.0+1
  
  # Testing

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.0 
  mocktail: ^0.3.0 

flutter:
  # assets:
  #   - assets/emojis/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Black.ttf
        - asset: assets/fonts/NotoSans-BlackItalic.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
        - asset: assets/fonts/NotoSans-ExtraBold.ttf
        - asset: assets/fonts/NotoSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
        - asset: assets/fonts/NotoSans-ExtraLight.ttf
        - asset: assets/fonts/NotoSans-ExtraLightItalic.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
        - asset: assets/fonts/NotoSans-Light.ttf
        - asset: assets/fonts/NotoSans-LightItalic.ttf
        - asset: assets/fonts/NotoSans-Medium.ttf
        - asset: assets/fonts/NotoSans-MediumItalic.ttf
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-SemiBold.ttf
        - asset: assets/fonts/NotoSans-SemiBoldItalic.ttf
        - asset: assets/fonts/NotoSans-Thin.ttf
        - asset: assets/fonts/NotoSans-ThinItalic.ttf
    # - family: OpenSans
    #   fonts:
    #     - asset: assets/fonts/OpenSans-ExtraBold.ttf
    #       weight: 800
    #     - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
    #       weight: 800
    #       style: italic
    #     - asset: assets/fonts/OpenSans-Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/OpenSans-BoldItalic.ttf
    #       weight: 700
    #       style: italic
    #     - asset: assets/fonts/OpenSans-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
    #       weight: 600
    #       style: italic
    #     - asset: assets/fonts/OpenSans-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/OpenSans-MediumItalic.ttf
    #       weight: 500
    #       style: italic
    #     - asset: assets/fonts/OpenSans-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/OpenSans-Italic.ttf
    #       weight: 400
    #       style: italic

flutter_gen:
  output: lib/src/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true

  package_parameter_enabled: true
  assets:
    outputs:
      exclude:
        - assets/emojis/*
