name: method_data
description: Repository for method.

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_remote_config: ^2.0.14
  method_core:

dev_dependencies:
  dart_code_metrics: ^4.17.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
