name: method_isar
description: Persistence for method.

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.0.1
  isar_flutter_libs: ^3.0.1

  method_core:
  method_repo:

dev_dependencies:
  build_runner: ^2.2.0
  dart_code_metrics: ^4.17.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  isar_generator: ^3.0.1